name: Deploy to GKE

on:
  push:
    paths:
      - 'src/**'
      - 'Dockerfile'
      - 'pom.xml'
      - '.github/workflows/deploy.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
      GKE_ZONE: ${{ secrets.GKE_ZONE }}
      GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
      GCP_SA_KEY: ${{ secrets.GCP_GKE_SA_KEY }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Cloud SDK for GKE
         uses: google-github-actions/setup-gcloud@v1
         with:
           service_account_key: ${{ secrets.GCP_GKE_SA_KEY }}
           project_id: ${{ secrets.GCP_PROJECT }}
           export_default_credentials: true
        

      - name: Authenticate and configure GKE
        run: |
          gcloud config set project $GCP_PROJECT
          gcloud config set compute/zone $GKE_ZONE
          gcloud container clusters get-credentials $GKE_CLUSTER



      - name: Log in to Docker Hub
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build Docker image
        run: |
          IMAGE_TAG=$(git rev-parse --short HEAD)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          docker build -t $DOCKER_USERNAME/todo-app:$IMAGE_TAG .

      - name: Push Docker image to Docker Hub
        run: |
          docker push $DOCKER_USERNAME/todo-app:$IMAGE_TAG

      - name: Deploy to GKE
        run: |
          kubectl set image deployment/todo-app todo-app=$DOCKER_USERNAME/todo-app:$IMAGE_TAG
          kubectl rollout status deployment/todo-app
